from django.urls import path
from . import views, reports

urlpatterns = [

    
    path('desktop/excel/', reports.desktop_excel, name='desktop-excel'),
    path('laptop/excel/', reports.laptop_excel, name='laptop-excel'),


    path('dashboard/', views.index, name='dashboard-index'),
    path('phone/', views.phone, name='dashboard-phone'),
    path('desktop/', views.desktop, name='dashboard-desktop'),
    path('laptop/', views.laptop, name='dashboard-laptop'),
    path('laptop/detail/<int:pk>/', views.laptop_details, name='dashboard-laptop-detail'),
    path('printer/', views.printer, name='dashboard-printer'),
    path('network/', views.network, name='dashboard-network'),
    path('monitor/', views.monitor, name='dashboard-monitor'),
    path('keyboard/', views.keyboard, name='dashboard-keyboard'),
    path('mouse/', views.mouse, name='dashboard-mouse'),
    path('accessory/', views.accessory, name='dashboard-accessory'),
    path('add/laptop/', views.add_laptop, name='dashboard-add-laptop'),
    path('add/desktop/', views.add_desktop, name='dashboard-add-desktop'),
    path('add/phone/', views.add_phone, name='dashboard-add-phone'),
    path('devices/', views.devices, name='dashboard-devices'),
    path('hdd/', views.hdd, name='dashboard-hdd'),
    path('lthdd/', views.LThdd, name='dashboard-lthdd'),
    path('ram/', views.ram, name='dashboard-ram'),
    path('ltram/', views.LTram, name='dashboard-ltram'),
    path('desktop/detail/<int:pk>/', views.desktop_details, name='dashboard-desktop-detail'),
    path('disconnect/desktop/monitor/<int:pk>/<int:pk1>/', views.disconnect_desktop_monitor, name='dashboard-disconnect-desktop-monitor'),
    path('connect/desktop/monitor/<int:pk>/', views.connect_desktop_monitor, name='dashboard-connect-desktop-monitor'),
    path('save/connect/monitor/<int:pk>/<int:pk1>/', views.save_connect_monitor, name='dashboard-save-connect-monitor'),
    path('disconnect/desktop/hdd/<int:pk>/<int:pk1>/', views.disconnect_desktop_hdd, name='dashboard-disconnect-desktop-hdd'),
    path('connect/desktop/hdd/<int:pk>/', views.connect_desktop_hdd, name='dashboard-connect-desktop-hdd'),
    path('save/connect/hdd/<int:pk>/<int:pk1>/', views.save_connect_hdd, name='dashboard-save-connect-hdd'),
    path('disconnect/desktop/ram/<int:pk>/<int:pk1>/', views.disconnect_desktop_ram, name='dashboard-disconnect-desktop-ram'),
    path('connect/desktop/ram/<int:pk>/', views.connect_desktop_ram, name='dashboard-connect-desktop-ram'),
    path('save/connect/ram/<int:pk>/<int:pk1>/', views.save_connect_ram, name='dashboard-save-connect-ram'),
    path('disconnect/laptop/lthdd/<int:pk>/<int:pk1>/', views.disconnect_laptop_lthdd, name='dashboard-disconnect-laptop-lthdd'),
    path('connect/laptop/lthdd/<int:pk>/', views.connect_laptop_lthdd, name='dashboard-connect-laptop-lthdd'),
    path('save/connect/lthdd/<int:pk>/<int:pk1>/', views.save_connect_lthdd, name='dashboard-save-connect-lthdd'),
    path('disconnect/laptop/ltram/<int:pk>/<int:pk1>/', views.disconnect_laptop_ltram, name='dashboard-disconnect-laptop-ltram'),
    path('connect/laptop/ltram/<int:pk>/', views.connect_laptop_ltram, name='dashboard-connect-laptop-ltram'),
    path('save/connect/ltram/<int:pk>/<int:pk1>/', views.save_connect_ltram, name='dashboard-save-connect-ltram'),
    path('disconnect/desktop/keyboard/<int:pk>/<int:pk1>/', views.disconnect_desktop_keyboard, name='dashboard-disconnect-desktop-keyboard'),
    path('connect/desktop/keyboard/<int:pk>/', views.connect_desktop_keyboard, name='dashboard-connect-desktop-keyboard'),
    path('save/connect/keyboard/<int:pk>/<int:pk1>/', views.save_connect_keyboard, name='dashboard-save-connect-keyboard'),
    path('disconnect/desktop/mouse/<int:pk>/<int:pk1>/', views.disconnect_desktop_mouse, name='dashboard-disconnect-desktop-mouse'),
    path('connect/desktop/mouse/<int:pk>/', views.connect_desktop_mouse, name='dashboard-connect-desktop-mouse'),
    path('save/connect/mouse/<int:pk>/<int:pk1>/', views.save_connect_mouse, name='dashboard-save-connect-mouse'),
    path('desktop/history/<int:pk>/', views.desktop_history, name='dashboard-desktop-history'),
    path('laptop/history/<int:pk>/', views.laptop_history, name='dashboard-laptop-history'),
]
