# Generated by Django 4.1.5 on 2023-04-18 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('Computer_Name', models.CharField(max_length=100, unique=True)),
                ('Desktop_Make', models.CharField(max_length=100)),
                ('Desktop_SN', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Processor', models.CharField(max_length=100)),
                ('Operating_System', models.CharField(choices=[('Win 10', 'Win 10'), ('Win 10 Pro', 'Win 10 Pro'), ('Win 8', 'Win 8'), ('Win 8.1', 'Win 8.1'), ('Win 8 Pro', 'Win 8 Pro'), ('Win 7', 'Win 7'), ('Win 7 Pro', 'Win 7 Pro')], max_length=10)),
                ('Office_Suite', models.CharField(max_length=10)),
                ('anti_virus', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Condition', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('Damaged', 'Damaged'), ('INACTIVE', 'INACTIVE')], max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('Computer_Name', models.CharField(max_length=100, unique=True)),
                ('Make', models.CharField(max_length=100)),
                ('Serial_Number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Processor', models.CharField(max_length=100)),
                ('Operating_System', models.CharField(choices=[('Win 10', 'Win 10'), ('Win 10 Pro', 'Win 10 Pro'), ('Win 8', 'Win 8'), ('Win 8.1', 'Win 8.1'), ('Win 8 Pro', 'Win 8 Pro'), ('Win 7', 'Win 7'), ('Win 7 Pro', 'Win 7 Pro')], max_length=10)),
                ('Office_Suite', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('anti_virus', models.CharField(max_length=50)),
                ('Condition', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('Damaged', 'Damaged'), ('INACTIVE', 'INACTIVE')], max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(choices=[('NE', 'NE'), ('HQ', 'HQ'), ('ER', 'ER'), ('SR', 'SR')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, unique=True)),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM_SN', models.CharField(max_length=100, unique=True)),
                ('RAM_Size', models.IntegerField(null=True)),
                ('RAM_make', models.CharField(max_length=50, null=True)),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='dashboard.desktop')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('Device_number', models.IntegerField(unique=True)),
                ('Make', models.CharField(choices=[('Huaweii', 'Huaweii'), ('Samsung', 'Samsung'), ('Tecno', 'Tecno')], max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('apk_version', models.CharField(max_length=100, null=True)),
                ('android_version', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('Condition', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('Damaged', 'Damaged'), ('INACTIVE', 'INACTIVE')], max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('man_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_number', to='user.profile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.zones')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mouse_SN', models.CharField(max_length=100, unique=True)),
                ('Mouse_make', models.CharField(max_length=50, null=True)),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouses', to='dashboard.desktop')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_SN', models.CharField(max_length=100, unique=True)),
                ('monitor_make', models.CharField(max_length=50, null=True)),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='dashboard.desktop')),
            ],
        ),
        migrations.CreateModel(
            name='LT_RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LT_RAM_SN', models.CharField(max_length=100, unique=True)),
                ('LT_RAM_Size', models.IntegerField(null=True)),
                ('LT_RAM_make', models.CharField(max_length=50, null=True)),
                ('LT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lt_rams', to='dashboard.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='LT_HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LT_HDD_SN', models.CharField(max_length=100, unique=True)),
                ('LT_HDD_model', models.CharField(max_length=50)),
                ('LT_Hard_disk_Size', models.IntegerField()),
                ('LT_Hard_disk_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=10)),
                ('LT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lt_hdds', to='dashboard.laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.station'),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_SN', models.CharField(max_length=100, unique=True)),
                ('Keyboard_make', models.CharField(max_length=50, null=True)),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboards', to='dashboard.desktop')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDD_SN', models.CharField(max_length=100, unique=True)),
                ('HDD_model', models.CharField(max_length=50)),
                ('Hard_disk_Size', models.IntegerField()),
                ('Hard_disk_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=10)),
                ('wk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdds', to='dashboard.desktop')),
            ],
        ),
        migrations.AddField(
            model_name='desktop',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.station'),
        ),
    ]
