# Generated by Django 4.1.5 on 2023-04-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('dashboard', '0002_alter_keyboard_wk_alter_monitor_wk_alter_mouse_wk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.station'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdds', to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='wk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboards', to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.station'),
        ),
        migrations.AlterField(
            model_name='lt_hdd',
            name='LT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt_hdds', to='dashboard.laptop'),
        ),
        migrations.AlterField(
            model_name='lt_ram',
            name='LT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt_rams', to='dashboard.laptop'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='wk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='wk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouses', to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='man_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_number', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zones'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rams', to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='station',
            name='region1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.region'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='region1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.region'),
        ),
    ]
