# Generated by Django 4.1.5 on 2023-04-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_desktop_assign_alter_desktop_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='wk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.desktop'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='wk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.desktop'),
        ),
    ]
