# Generated by Django 4.2.4 on 2023-08-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_historicaldesktop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='Desktop_SN',
            new_name='Serial_Number',
        ),
        migrations.RenameField(
            model_name='historicaldesktop',
            old_name='Desktop_SN',
            new_name='Serial_Number',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='imei',
            new_name='Serial_Number',
        ),
    ]
