# Generated by Django 4.2.4 on 2023-09-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_alter_hdd_wk_alter_keyboard_wk_alter_monitor_wk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(choices=[('NE', 'NE'), ('HQ', 'HQ'), ('ER', 'ER'), ('SR', 'SR'), ('WR', 'WR'), ('CR', 'CR')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_SN', models.CharField(max_length=150, unique=True)),
                ('p_make', models.CharField(max_length=100)),
                ('p_model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('No_Toner', models.IntegerField()),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Damaged', 'Damaged'), ('Repairs', 'Repairs'), ('Inactive', 'Inactive'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printerRegion', to='dashboard.region')),
            ],
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_type', models.CharField(max_length=50)),
                ('N_SN', models.CharField(max_length=150, unique=True)),
                ('N_make', models.CharField(max_length=100)),
                ('N_model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Damaged', 'Damaged'), ('Repairs', 'Repairs'), ('Inactive', 'Inactive'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NetworkRegion', to='dashboard.region')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrinter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('P_SN', models.CharField(db_index=True, max_length=150)),
                ('p_make', models.CharField(max_length=100)),
                ('p_model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('No_Toner', models.IntegerField()),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Damaged', 'Damaged'), ('Repairs', 'Repairs'), ('Inactive', 'Inactive'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.region')),
            ],
            options={
                'verbose_name': 'historical printer',
                'verbose_name_plural': 'historical printers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNetworking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('N_type', models.CharField(max_length=50)),
                ('N_SN', models.CharField(db_index=True, max_length=150)),
                ('N_make', models.CharField(max_length=100)),
                ('N_model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Damaged', 'Damaged'), ('Repairs', 'Repairs'), ('Inactive', 'Inactive'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.region')),
            ],
            options={
                'verbose_name': 'historical networking',
                'verbose_name_plural': 'historical networkings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcatrilage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('C_SN', models.CharField(db_index=True, max_length=100)),
                ('C_model', models.CharField(max_length=50)),
                ('C_make', models.CharField(max_length=50)),
                ('C_color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Full', 'Full'), ('used', 'used'), ('Empty', 'Empty'), ('Ingenuine', 'Ingenuine'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.region')),
            ],
            options={
                'verbose_name': 'historical catrilage',
                'verbose_name_plural': 'historical catrilages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='catrilage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_SN', models.CharField(max_length=100, unique=True)),
                ('C_model', models.CharField(max_length=50)),
                ('C_make', models.CharField(max_length=50)),
                ('C_color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Full', 'Full'), ('used', 'used'), ('Empty', 'Empty'), ('Ingenuine', 'Ingenuine'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TonerRegion', to='dashboard.region')),
            ],
        ),
    ]
