# Generated by Django 4.2.4 on 2023-09-12 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_region_region_name_printer_networking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Computer_Name', models.CharField(max_length=100, unique=True)),
                ('Make', models.CharField(max_length=100)),
                ('Serial_Number', models.CharField(max_length=100, unique=True)),
                ('Processor', models.CharField(max_length=100)),
                ('Operating_System', models.CharField(choices=[('Win 10', 'Win 10'), ('Win 10 Pro', 'Win 10 Pro'), ('Win 8', 'Win 8'), ('Win 8.1', 'Win 8.1'), ('Win 8 Pro', 'Win 8 Pro'), ('Win 7', 'Win 7'), ('Win 7 Pro', 'Win 7 Pro')], max_length=10)),
                ('Office_Suite', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('anti_virus', models.CharField(max_length=50)),
                ('Condition', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('Damaged', 'Damaged'), ('INACTIVE', 'INACTIVE')], max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.station')),
            ],
        ),
    ]
