# Generated by Django 4.2.4 on 2023-09-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_laptop1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lt_hdd',
            name='LT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt_hdds', to='dashboard.laptop1'),
        ),
        migrations.AlterField(
            model_name='lt_ram',
            name='LT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt_rams', to='dashboard.laptop1'),
        ),
    ]
