# Generated by Django 4.2.4 on 2023-08-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField()),
                ('request_type', models.CharField(choices=[('assign', 'assign'), ('movement', 'movement'), ('repair', 'repair'), ('maintenance', 'maintenance')], max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(unique=True)),
                ('request_type', models.CharField(default='repair', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('Assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_repair', to='user.profile')),
                ('R_Technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Repair_Tech', to='user.profile')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(unique=True)),
                ('request_type', models.CharField(default='movement', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('Assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_move', to=settings.AUTH_USER_MODEL)),
                ('move_Technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_tech', to='user.profile')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_requesters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_number', models.IntegerField()),
                ('request_type', models.CharField(choices=[('assign', 'assign'), ('movement', 'movement'), ('repair', 'repair'), ('maintenance', 'maintenance')], max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical request',
                'verbose_name_plural': 'historical requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRepair',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_number', models.IntegerField(db_index=True)),
                ('request_type', models.CharField(default='repair', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('R_Technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical repair',
                'verbose_name_plural': 'historical repairs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_number', models.IntegerField(db_index=True)),
                ('request_type', models.CharField(default='movement', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('move_Technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical movement',
                'verbose_name_plural': 'historical movements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAssign',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_number', models.IntegerField(db_index=True)),
                ('request_type', models.CharField(default='assign', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('Technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical assign',
                'verbose_name_plural': 'historical assigns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(unique=True)),
                ('request_type', models.CharField(default='assign', max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('Assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='user.profile')),
                ('Technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assign_Tech', to='user.profile')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
