# Generated by Django 4.2.4 on 2023-08-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(unique=True)),
                ('request_type', models.CharField(default='Issuance', max_length=100)),
                ('device', models.CharField(choices=[('phones', 'Phone'), ('desktop', 'Desktop'), ('laptop', 'Laptop')], max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('Approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approved_by', to=settings.AUTH_USER_MODEL)),
                ('Issued', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Issued_to', to=settings.AUTH_USER_MODEL)),
                ('Technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Issuance_Tech', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Issuance_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIssuance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_number', models.IntegerField(db_index=True)),
                ('request_type', models.CharField(default='Issuance', max_length=100)),
                ('device', models.CharField(choices=[('phones', 'Phone'), ('desktop', 'Desktop'), ('laptop', 'Laptop')], max_length=100)),
                ('device_serial', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('comment', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='open', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Approver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('Issued', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('Technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical issuance',
                'verbose_name_plural': 'historical issuances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
