# Generated by Django 4.2.4 on 2023-09-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_request_historicaltask_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequest',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterField(
            model_name='assign',
            name='request_type',
            field=models.CharField(default='issuance', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalassign',
            name='request_type',
            field=models.CharField(default='issuance', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalissuance',
            name='device',
            field=models.CharField(choices=[('phones', 'phone'), ('desktop', 'desktop'), ('laptop', 'laptop')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltask_request',
            name='request_type',
            field=models.CharField(choices=[('issuance', 'issuance'), ('movement', 'movement'), ('repair', 'repair'), ('maintenance', 'maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='device',
            field=models.CharField(choices=[('phones', 'phone'), ('desktop', 'desktop'), ('laptop', 'laptop')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task_request',
            name='request_type',
            field=models.CharField(choices=[('issuance', 'issuance'), ('movement', 'movement'), ('repair', 'repair'), ('maintenance', 'maintenance')], max_length=100),
        ),
        migrations.DeleteModel(
            name='HistoricalRequest',
        ),
    ]
